// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXODJssoh_lDLdLDLVQCbNppErqrv2Xjk',
    appId: '1:251011168155:web:9e44ec187488345804133e',
    messagingSenderId: '251011168155',
    projectId: 'notes-flutter-app-project',
    authDomain: 'notes-flutter-app-project.firebaseapp.com',
    storageBucket: 'notes-flutter-app-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3gqqppc5ap-IDYXBLZeNXg_8n7hIwZd8',
    appId: '1:251011168155:android:5ce4bcf4d8ac14d304133e',
    messagingSenderId: '251011168155',
    projectId: 'notes-flutter-app-project',
    storageBucket: 'notes-flutter-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn9L7TIMU12nKhh5qHXwxb8SdrtWQe3mI',
    appId: '1:251011168155:ios:f62c8ed9f59f8c9504133e',
    messagingSenderId: '251011168155',
    projectId: 'notes-flutter-app-project',
    storageBucket: 'notes-flutter-app-project.appspot.com',
    iosClientId: '251011168155-38d20utmq9p8a9tiqvvl4fmkm4epj4uj.apps.googleusercontent.com',
    iosBundleId: 'co.uk.abad',
  );
}
